### PR TITLE
EMAIL WASTE - DRAFT post

### PR DESCRIPTION
**Pull request by wpschaub**
Share how I am managing my email, reducing noise, and combating the invaluable WASTE created by the flood of emails.

### CODE REVIEW

**Review by wsbctechnicalblog — DISMISSED** [review]
Great initiative, would it be possible to add

**Comment by wpschaub** [comment]
@wsbctechnicalblog ... possible to add what?

**Comment by wsbctechnicalblog** [comment]
> @wsbctechnicalblog ... possible to add what?

Sorry about the glitch, @wpschaub. I meant to ask if it would be possible to add @AndreKaminski's great recommendation to always prepend every outgoing email with a qualifier in the subject line. For example, [INFO] for non-actionable emails, [URGENT] to grab everyone's attention, and so on. Andre will know more details (I apologize, I wasn't able to quickly find Andre's Sunday email where he elaborated on this; I though it was a really great productivity boost and decided to give it a try myself).

**Review by erwsch1 — DISMISSED** [review]

**Comment by wsbctechnicalblog** [comment]
@wpschaub should I publish it now?

**Comment by wpschaub** [comment]
You can, but you requested a change. Not sure when I will find the 10min I need to update it today.

**Comment by wsbctechnicalblog** [comment]
> You can, but you requested a change. Not sure when I will find the 10min I need to update it today.

@wpschaub it was more a suggestion. As it is, it seems good to go. But it's your call.

**Review by wsbctechnicalblog — APPROVED** [review]

**Review by erwsch1 — APPROVED** [review]

**Pull request merged**
