### PR TITLE
Fix Date

### PR DESCRIPTION
**Pull request by wpschaub**

### CODE REVIEW

**Comment by wpschaub** [comment]
@wsbctechnicalblog please can you double check the dates of my posts before approving them? I managed to back in the future again :(

**Review by wsbctechnicalblog — APPROVED** [review]

**Comment by wsbctechnicalblog** [comment]
> @wsbctechnicalblog please can you double check the dates of my posts before approving them? I managed to back in the future again :(

I'll try to make it a habit to check the publish dates before merging.

**Comment by wpschaub** [comment]
@wsbctechnicalblog This one is good to go!

**Comment by wpschaub** [comment]
@wsbctechnicalblog I notice that when you completed the last PR the md file made its way to master, however, no html files is in the root? Was the html generation not run?

**Pull request merged**
