### PR TITLE
2022.02.25 - First DRAFT meeting outline

### PR DESCRIPTION
**Pull request by wpschaub**

### CODE REVIEW

**Comment by AndreKaminski** [comment]
Let's have a quick discussion first so we don't throw the baby out with bath water

**Review by erwsch1 — DISMISSED** [review]

**Comment by wpschaub** [comment]
@AndreKaminski I have defused a lot of the text - hope it reads better and less negative. Queueing the article for March/9 if I can get your and @erwsch1 approval.

**Comment by wpschaub** [comment]
@AndreKaminski I have defused a lot of the text - hope it reads better and less negative. Queueing the article for March/9 if I can get your and @erwsch1 approval.

**Review by erwsch1 — DISMISSED** [review]

**Comment by erwsch1** [comment]
Great article Willy. Defusing successful!

**Review by AndreKaminski — COMMENTED** [review]
It looks pretty close. I would suggest to remove the '4 hours to relax', as it might create a wrong impression. W/r to 'decline all double bookings', I still want to be aware of some meetings (sometimes they are re-occurring meetings), that I might attend in the future. I don't decline them as they would disappear from my calendar, but just mark them as tentative. Yes, it doesn't declutter the calendar, but keeps me aware. As a matter of fact, I can still access notes of these meetings if I need or recordings. So this is personal time management technique that depends on style. Thus I would be careful with 'to decline all double bookings' statement.

**Comment by wpschaub** [comment]
@AndreKaminski great feedback! I removed the 4 hours as suggested and elaborated on what I mean with double bookings. I too keep meetings in my calendar for reference, but do not commit (accept) them. With double bookings I am referring to me peeking into your calendar, seeing that you have a committed meeting at X, but still send you an invite to meet at the same time.

**Review by AndreKaminski — COMMENTED** [review]
Looks great Willy

**Review by AndreKaminski — APPROVED** [review]
good to go from my side

**Pull request merged**
