### PR TITLE
Dojo events

### PR DESCRIPTION
**Pull request by wsbctechnicalblog**

### CODE REVIEW

**Comment by wpschaub** [comment]
@wsbctechnicalblog  can you add the download section to download the overview poster and the dojo working agreement. The dojo poster pdf is on our SharePoint server and should be added to the documents folder.

This would make the post consistent with the others and point to the artifacts.

**Comment by wpschaub** [comment]
We will have to update the Date before publishing the posts, so that we have the correct sequence, starting with the CoE. I intentionally made my working group and CoP PR DRAFT, so that I remember to make the final tweaks before we click the launch button.

**Comment by wpschaub** [comment]
@wsbctechnicalblog We will have to update the Date before publishing the posts, so that we have the correct sequence, starting with the CoE. I intentionally made my working group and CoP PR DRAFT, so that I remember to make the final tweaks before we click the launch button.

**Comment by wsbctechnicalblog** [comment]
There is a typo in the poster, I cannot edit it.

**Comment by wsbctechnicalblog** [comment]
> @wsbctechnicalblog can you add the download section to download the overview poster and the dojo working agreement. The dojo poster pdf is on our SharePoint server and should be added to the documents folder.
> 
> This would make the post consistent with the others and point to the artifacts.

I've added the Working Agreement poster.

**Comment by wpschaub** [comment]
@wsbctechnicalblog I changed the meta data date to 11/11 to match the publishing date next week and added the poster downloads at the end of your post. You must do a fetch before you make further changes to avoid merge hell! Hope you like.

**Comment by wpschaub** [comment]
@wsbctechnicalblog can you replace events tag with ceremony tag? Tag events is used to report back on events.

**Comment by wsbctechnicalblog** [comment]
Closing this because it contains a lot of noise with all the generated HTML files. Opened a simplified "Dojo events" PR instead.

**Pull request closed without merging**
