### PR TITLE
Complete first review DRAFT for Part 4 of the pipeline series

### PR DESCRIPTION
**Pull request by wpschaub**
In this post we demonstrate the power of the new multi-stage YAML pipelines to make even our most critical security engineers smile from ear to ear.

Both @erwsch1 and @604kev must approve this PR before we publish!

### CODE REVIEW

**Review by solicitfeedback — APPROVED** [review]

**Review by erwsch1 — APPROVED** [review]

**Comment by solicitfeedback** [comment]
> In this post we demonstrate the power of the new multi-stage YAML pipelines to make even our most critical security engineers smile from ear to ear.
> 
> Both @erwsch1 and @604kev must approve this PR before we publish!

Do you want me to wait for @604kev review or should I merge now?

**Comment by wpschaub** [comment]
Wait. I am meeting with @604kev today.

**Comment by solicitfeedback** [comment]
> Wait. I am meeting with @604kev today.

Just wanted to remind you that merging does not imply publishing.

**Comment by wpschaub** [comment]
Understand, however, I would like to give all reviewers a chance to comment and for us to polish the content before it is merged with master. Once the PR is completed, the feature branch evaporates and we would have to submit another PR to change or revert changes.

**Comment by 604kev** [comment]
PR reviewed, looks good :)

**Review by littleswancode — APPROVED** [review]
DevSecOps approved!

**Pull request merged**
