### PR TITLE
updated the latest content and streamlined the branch

### PR DESCRIPTION
**Pull request by wsbctechnicalblog**

### CODE REVIEW

**Comment by wsbctechnicalblog** [comment]
Simplified the review by not including the generated HTML files. The old dojo branch is now obsolete.

**Comment by wpschaub** [comment]
@wsbctechnicalblog Does this replace the Dojo PR?

If yes, can you replace the event tag with the ceremony tag? Tag event is used to report back on a hosted event.

**Comment by wpschaub** [comment]
@wsbctechnicalblog just noticed that the *.md file is empty?!?

**Comment by wsbctechnicalblog** [comment]
> @wsbctechnicalblog just noticed that the *.md file is empty?!?

Heh, in a hurry forgot to save before committing. One for the hall of shame.

**Pull request merged**
