### PR TITLE
Self-service automation - A dream turns into reality

### PR DESCRIPTION
**Pull request by wpschaub**
Document our automation dream and the drop-the-mic demo

### CODE REVIEW

**Comment by wpschaub** [comment]
@wsbctechnicalblog @erwsch1 are you OK with us sharing our advances to this level of detail? This is where the rubber meets the tarmac and where we can start investing in automation and reduction in waste. I suggest that we do NOT publish until we had the emgimeetring excellence session on Friday.

**Review by erwsch1 — DISMISSED** [review]

**Review by wsbctechnicalblog — APPROVED** [review]
Excellent article. Will wait for after our technical excellence session on Friday to publish.

**Review by erwsch1 — APPROVED** [review]

**Comment by wpschaub** [comment]
@wsbctechnicalblog you can click the launch button.

**Comment by wpschaub** [comment]
@wsbctechnicalblog you can click ythe launch button.

**Pull request merged**
