### PR TITLE
EDO ce Journal Entry #2

### PR DESCRIPTION
**Pull request by wpschaub**
Second journal entry chatting about "Why EDO Ce" and top three achievements.

### CODE REVIEW

**Review by wsbctechnicalblog — COMMENTED** [review]
Great overview. One typo:

On line 9 you wrote "it is time to shared and update our team journal". I believe you wanted to write time to SHARE, not SHARED. Am I reading it correctly?

My favourite part of our first 90 days journey (which hasn't ended yet) is formulating clear expectations coming from the stakeholders. That creates clarity in my mind, which is very important to me.

**Comment by wpschaub** [comment]
Fixed typo, thank you for catching it @wsbctechnicalblog.
Also added your favourite part.

**Review by wsbctechnicalblog — APPROVED** [review]
Thanks for adding my favourite part!

**Review by erwsch1 — APPROVED** [review]

**Comment by wsbctechnicalblog** [comment]
@wpschaub when would you like me to publish?

**Comment by wpschaub** [comment]
@wsbctechnicalblog  GO for launch!

**Pull request merged**
