### PR TITLE
Re-submit journal 2

### PR DESCRIPTION
**Pull request by wpschaub**
Second journal of the EDO Ce team.

### CODE REVIEW

**Comment by wpschaub** [comment]
@wsbctechnicalblog here is the journal #2 DRAFT again. It is important that @AndreKaminski approves the PR before we publish, because I want to be 100% sure that his upcoming message, aligns with my journal posts.

**Review by wsbctechnicalblog — DISMISSED** [review]

**Review by erwsch1 — DISMISSED** [review]

**Review by AndreKaminski — DISMISSED** [review]
This looks good!

**Comment by wsbctechnicalblog** [comment]
@wpschaub should I wait till Monday to publish?

**Comment by wpschaub** [comment]
@wsbctechnicalblog yes, please publish on Monday, as the date is set to the 20th.

**Review by erwsch1 — APPROVED** [review]

**Pull request merged**
