### PR TITLE
Willys/wsbc-best-place

### PR DESCRIPTION
**Pull request by wpschaub**
First DRAFT of my WIIFM article for our A/E/W discussion.

### CODE REVIEW

**Review by ShayVannery — DISMISSED** [review]

**Review by AndreKaminski — COMMENTED** [review]
I am missing here cool technologies that we are either using currently, or looking to use in the future

**Review by erwsch1 — DISMISSED** [review]

**Comment by wpschaub** [comment]
@AndreKaminski I am collaborating with our CoE to identify cool stuff that we can mention.

**Review by erwsch1 — DISMISSED** [review]

**Comment by wpschaub** [comment]
@AndreKaminski I have added a few of the cool technologies we are focusing on at the moment. I can work with Laurent to create a technology map for a future post.

**Review by ShayVannery — APPROVED** [review]

**Review by ShayVannery — DISMISSED** [review]

**Review by erwsch1 — DISMISSED** [review]

**Review by AndreKaminski — COMMENTED** [review]
as for technologies list I would suggest to list from most to least exciting. API, Mobile, Performance and UI testing might not be the most exciting - most of organizations do this (sorry Adi :) ). But what's about TDD, BDD, Domain Driven Design, Shift-Left and so on.

as for your comment about WIIFM - are you prepared to walk the talk with replacing other 4-letter acronyms like YAML, or CI/CD in this post? :)

**Comment by wpschaub** [comment]
@AndreKaminski I updated the TLAs and added a few items to the list of cool stuff. I also made a comment that it is alphabetically, not most to least important sorted, as that sort would depend on the reader.

@erwsch1 @ShayVannery @604kev @adichourasiya what other cool processes and/or products should I mention?

**Review by erwsch1 — DISMISSED** [review]

**Review by AndreKaminski — COMMENTED** [review]
It is not that I am fixated on some things but putting my product management/marketing hat, you want to grab someone's attention in the first lines. Our attention span is very short, and people tend to skip rest of paragraph after looking at the first sentence. This is like with movies. Notice how James Bond movies start. Before even title appears, there is an exciting scene that draws attention. This makes sure that the viewer becomes engaged. The first few minutes matter the most, how the rest will be perceived. Similarly with music, and so on. I would suggest that you bring up to the top the stuff that is new and would excite me as a reader. Otherwise I think we miss the opportunity. Anyway, this is just my opinion, and I don't mind approving it as is

**Comment by wpschaub** [comment]
@AndreKaminski great feedback and I agree the first few lines should grab the readers attention. I will update it tonight to most to least interesting through my lens - which will reflect the team's priorities.

**Comment by wpschaub** [comment]
@AndreKaminski I made a quick update during the last training break to get the discussion / feedback started. Anyone agreeing with the new list or do you feel one or more items should bubble to the top? ... and why?
cc @ShayVannery @erwsch1

**Review by AndreKaminski — APPROVED** [review]

**Review by erwsch1 — APPROVED** [review]

**Pull request merged**
