### PR TITLE
2021-01-28 - Journal 3 - Tweaking the trajectory of a innovation-minded team?

### PR DESCRIPTION
**Pull request by wpschaub**
Reporting from the control center

### CODE REVIEW

**Comment by wpschaub** [comment]
Image #7 is still missing as I have not yet received the "thumbs up" from all team members to include their mug 
shot.

**Comment by wpschaub** [comment]
@AndreKaminski here is my DRAFT post for the meetup session, to be published after the live session. Candid feedback welcome.
cc @wsbctechnicalblog

**Comment by wpschaub** [comment]
@AndreKaminski @wsbctechnicalblog any feedback on how to improve the message and content of the meetup session?

**Review by AndreKaminski — COMMENTED** [review]
this looks good although I cannot see images

**Comment by wpschaub** [comment]
@AndreKaminski my bad - the images are now lighting up in this latest update: https://github.com/wsbctechnicalblog/wsbctechnicalblog.github.io/blob/116ff8ecd9319c7a353d39bc1dced19262655071/content/common-engineering-journal-3.md

**Comment by AndreKaminski** [comment]
Looks good

**Review by wsbctechnicalblog — APPROVED** [review]

**Pull request merged**
