### PR TITLE
Pipelines - Why bother and what are our nightmares and options?

### PR DESCRIPTION
**Pull request by wpschaub**
This is the first of a series of Azure Pipeline posts to take the reader on our journey of pipelines.

@solicitfeedback the PR must be approved by @erwsch1 before we merge!

### CODE REVIEW

**Review by solicitfeedback — DISMISSED** [review]
Very timely post. We'll use it whenever someone asks "why unified pipelines?"

**Review by solicitfeedback — APPROVED** [review]
Exciting series. This will be the definitive guide!

**Review by vegantiger8 — APPROVED** [review]
Looks good...

**Comment by wpschaub** [comment]
@solicitfeedback it looks as if @erwsch1 has not yet reviewed and approved the PR. Should not have been merged. Can you defer publication until @erwsch1 has had a chance to review?

**Comment by solicitfeedback** [comment]
> @solicitfeedback it looks as if @erwsch1 has not yet reviewed and approved the PR. Should not have been merged. Can you defer publication until @erwsch1 has had a chance to review?

Oops, sorry my bad. I think we should either impose branch policy with minimum three approvers, or if we stay with two approvers, specify which two must approve.

**Pull request merged**
