### PR TITLE
Enacting Governance through  Manifestos and Guardrails

### PR DESCRIPTION
**Pull request by wpschaub**
A discussion whether we can enact governance through engeneering friendlier manifestos and guardrails, and whether mob guardrailing is an option.

### CODE REVIEW

**Comment by wpschaub** [comment]
@604kev @said-akram-wcbbc @wsbctechnicalblog @erwsch1 An unusual blog post proposal from me to suggest us trying "mob guardrailing" in the work groups to improve awareness, advocacy, and support for our guardrails.

**Comment by wsbctechnicalblog** [comment]
Absolutely LOVE this post! Brilliant. I'm all for it! Thank you @wpschaub 💯

**Review by wsbctechnicalblog — APPROVED** [review]

**Review by erwsch1 — APPROVED** [review]

**Comment by wsbctechnicalblog** [comment]
@wpschaub It's ready to be merged. Should I pull the pin on the hand grenade or wait for more reviews?

**Comment by wpschaub** [comment]
@wsbctechnicalblog pull the pin :)

**Pull request merged**
