### PR TITLE
Willys/381918-working-group

### PR DESCRIPTION
**Pull request by wpschaub**
First DRAFT of the working group ceremony, within context of the CoE.

### CODE REVIEW

**Review by sben101 — DISMISSED** [review]

**Review by wsbctechnicalblog — CHANGES_REQUESTED** [review]
Great summary of the role and the intent of working groups. One thing I wasn't able to see in the explanation (perhaps I somehow missed it) is: when forming a working group, we need to clearly specify how will we know if the working group was successful on its mission? In other words, we need clear and crisp acceptance criteria describing stakeholders' and sponsors' expectations.

**Comment by wpschaub** [comment]
@wsbctechnicalblog every one of our ceremonies has the "Terms of Reference" as the first requirement, which defines the vision, the goals, and the hypothesis/problem to solve.

**Review by AndreKaminski — COMMENTED** [review]
The only comment from my side would be to provide context w/r to lifespan. The CoE has really long lifespan, that is terminated by a technology, approach of philosophy becoming obsolete. For example if we had On Prem Engineering CoE, once we move fully to the cloud, it will be terminated. During the decline phase, the membership, governance, and vision will become stale. This is where CE should identify the trend and possibly start the process of termination.

**Comment by wpschaub** [comment]
@AndreKaminski I updated the CoE post, see https://github.com/wsbctechnicalblog/wsbctechnicalblog.github.io/pull/223, which is the first of our series of ceremony posts.

**Review by wsbctechnicalblog — APPROVED** [review]

**Pull request merged**
