### PR TITLE
willys/280171

### PR DESCRIPTION
**Pull request by wpschaub**
Welcome back to another installment of pipeline wizardry. In this latest post, part 8, we are delving into the world of continuous deployment (CD).

Apart from part 8, I am fine tuning the breadcrumbs for the series and cleaning up all the tags I have used to be consistent across all my posts. Main file: moving-hundreds-of-pipeline-snowflakes-part8.md

### CODE REVIEW

**Comment by wpschaub** [comment]
@alexbunardzic, @said-akram-wcbbc, and @604kev can you scan the first DRAFT of part 8 (CD) and give me candid and actionable feedback? What is missing? What must I emphasize more? What is fluff, noise?

Enjoy the rest of the weekend!

**Review by wsbctechnicalblog — CHANGES_REQUESTED** [review]
I would prefer stronger wording in the post summary. Instead of "Continuous Deployment seems important", I'd like to move into "Continuous Deployment is the most important ingredient of the DevOps practice". It is the holy grail of our profession.

**Comment by wpschaub** [comment]
@wsbctechnicalblog @alexbunardzic I tweaked the summary, using your suggestion as a baseline. I changed "most important" to "pivotal" as CD cannot function without the rest of the continuous delivery pipeline and more importantly, to stop a potential feud of what is most important. Also changed DevOps practice to DevOps mindset.

**Review by wsbctechnicalblog — DISMISSED** [review]

**Comment by wpschaub** [comment]
@wsbctechnicalblog I changed PR back to DRAFT as I still have to update an image placeholder. The Kevin said so image.

**Comment by wpschaub** [comment]
@wsbctechnicalblog I changed PR back to DRAFT as I still have to update an image placeholder. The Kevin said so image.

**Comment by wpschaub** [comment]
Updated the missing content and image at the end. Still working on refining the "Kevin said so" image.

**Review by erwsch1 — APPROVED** [review]

**Review by said-akram-wcbbc — APPROVED** [review]

**Review by wsbctechnicalblog — APPROVED** [review]

**Pull request merged**
