### PR TITLE
Willys/301174

### PR DESCRIPTION
**Pull request by wpschaub**
@wsbctechnicalblog should we add quick reference posts, such as this, to our technical blog/? If yes, is "Cheat Sheets" a good tag, or should we call them "Nuggets?"

If this is useful content, I will also add another for the blueprint pipeline quick reference poster.

### CODE REVIEW

**Comment by wsbctechnicalblog** [comment]
Brilliant idea! Let's do it!

**Comment by wpschaub** [comment]
@wsbctechnicalblog we need to triple check the published post before we make noise. The cheat sheet contains a lot of special character which shows A OK in markdown, but we need to ensure the conversion to HTML does not break anything.

**Comment by wsbctechnicalblog** [comment]
@wsbctechnicalblog I like "Cheat sheets"

**Comment by wsbctechnicalblog** [comment]
@wsbctechnicalblog I'll triple check generated HTML & alert you if anything did not get converted properly.

**Review by said-akram-wcbbc — APPROVED** [review]

**Review by wsbctechnicalblog — APPROVED** [review]

**Pull request merged**
