### PR TITLE
Stop the context switching, reduce waste, and focus on value

### PR DESCRIPTION
**Pull request by wpschaub**
A nonm-technical post that will help us focus and deliver better technical solutions!

### CODE REVIEW

**Review by erwsch1 — DISMISSED** [review]

**Review by erwsch1 — DISMISSED** [review]

**Review by erwsch1 — DISMISSED** [review]

**Comment by wpschaub** [comment]
@wsbctechnicalblog you could launch this one next, so that we break the techie stuff with a non-technical post :)

**Review by wsbctechnicalblog — APPROVED** [review]
I love this. People need to be told that busyness is NOT a badge of honour!

**Comment by wpschaub** [comment]
@erwsch1 I made another small tweak in the TOC page, which reset your vote. Is there anything in this post that may unsettle non-techies?

**Review by erwsch1 — APPROVED** [review]

**Comment by erwsch1** [comment]
Hi Willy,

No concerns at all from me. 

Thanks,
Erwin

**Pull request merged**
