### PR TITLE
willys/307841-FF

### PR DESCRIPTION
**Pull request by wpschaub**
Create a journal for the feature-flag lunch&learn session.

### CODE REVIEW

**Review by erwsch1 — DISMISSED** [review]

**Review by wsbctechnicalblog — DISMISSED** [review]

**Comment by wsbctechnicalblog** [comment]
Is this one good to go?

**Comment by wpschaub** [comment]
@wsbctechnicalblog as soon as @christine-ozeroff has clicked approve.  I will try an schedule a quick chat with her to give her a tour of GitHub and the review process.

**Review by christine-ozeroff — APPROVED** [review]
Looks good!  Thanks for updating the text I mentioned.

**Review by christine-ozeroff — DISMISSED** [review]

**Review by wsbctechnicalblog — APPROVED** [review]

**Review by christine-ozeroff — APPROVED** [review]

**Comment by wsbctechnicalblog** [comment]
Let me know when you want me to publish this, @wpschaub

**Comment by wpschaub** [comment]
@wsbctechnicalblog this one is also good to go, now that @christine-ozeroff has given the OK.

**Pull request merged**
