### PR TITLE
removes demo post

### PR DESCRIPTION
**Pull request by wsbctechnicalblog**
Need to remove Willy's demo post that was created during the dry run of the demo.

### CODE REVIEW

**Review by wpschaub — APPROVED** [review]
@alexbunardzic I was hoping the demo would remain. However, by removing it, it allows me to demo why images are not showing up when editing new posts. The markdown has to reference the /images folder, but when submitting new content we add images to /content/images.

**Comment by wsbctechnicalblog** [comment]
@wpschaub if you prefer, we can keep the demo.

**Comment by wpschaub** [comment]
@alexbunardzic 
No, nuke the demo. Just to clarify, should contributors add markdown files to /content and images to /content/images or /images as part of their PR? I will use an existing image tomorrow.

**Comment by wpschaub** [comment]
@alexbunardzic you can complete this PR. We can cleanup the duplicate image folders after the demo when we prepare the blog for showtime.

**Pull request merged**
