### PR TITLE
First journal DRAFT

### PR DESCRIPTION
**Pull request by wpschaub**
@wsbctechnicalblog is this what you are looking for in the EDO Ce journal? If yes, we must get @AndreKaminski to approve as we are reporting on one of the EDO teams and as I am hoping we will get  a supportive blog from him :)

### CODE REVIEW

**Review by wsbctechnicalblog — CHANGES_REQUESTED** [review]
Very nice snapshot of the current situation. One change request: on line 52 it reads "Make requirements less dump"; I think you meant 'dumb', not 'dump'?

**Review by AndreKaminski — COMMENTED** [review]
A few changes from my side:

- since this is read externally, and it reflects on our organization, I would suggest to tone down the statement with _'I was flubbergasted_'.
- '_As soon as ownership is transferred to a sustainment, maintenance, site reliability, or any other team'_ - this is not entirely true in DevOps - the ownership should stay with the team that developed the application, it might be however temporarily supported by SREs or other teams. I know that currently this might feel like this, but this is what I would like to change next year
- _'autonomy without guidance'_ - I would suggest to change to 'autonomy without guardrails'
- _'working active groups'_ - shouldn't this be 'active working groups'?

**Comment by wpschaub** [comment]
@AndreKaminski thank you for the great feedback.

- Toned down the "flabbergasted" - please check.
- I agree, this is a RED FLAG, a DevOps anti-pattern, and something we need to address. I reworded the section to emphasize that it is NOT a mindset we encourage.
- Good suggestion - done.
- Good catch - fixed.

**Comment by wpschaub** [comment]
@AndreKaminski thank you for the great feedback.

- Toned down the "flabbergasted" - please check.
- I agree, this is a RED FLAG, a DevOps anti-pattern, and something we need to address. I reworded the section to emphasize that it is NOT a mindset we encourage.

**Review by erwsch1 — DISMISSED** [review]

**Review by wsbctechnicalblog — APPROVED** [review]

**Comment by wsbctechnicalblog** [comment]
@wpschaub when would you like me to publish this?

**Comment by wpschaub** [comment]
@wsbctechnicalblog  it is good to go, as soon as @AndreKaminski approves the PR.

**Comment by wsbctechnicalblog** [comment]
> @wsbctechnicalblog it is good to go, as soon as @AndreKaminski approves the PR.

OK, I'm standing by...

**Comment by AndreKaminski** [comment]
@wpschaub it looks good, thank you

**Comment by wsbctechnicalblog** [comment]
@wpschaub we need one more approval and then I can merge & publish.

**Review by erwsch1 — APPROVED** [review]

**Review by AndreKaminski — APPROVED** [review]

**Pull request merged**
