### PR TITLE
saida/297172

### PR DESCRIPTION
**Pull request by wpschaub**
@said-akram-wcbbc, here is a dump of my thoughts for your app-type post. Please polish and/or panel-beat as needed :) Only the *part7* files are relevant. Please add @erwsch1 as reviewer when you set the PR from DRAFT to Ready for Review.

Updated part 1-6 to reference part 7 in the breadcrumbs and part 1 TOC.

@alexbunardzic, please review and advise what needs to be expanded on. Do **NOT** publish, until Said submit the final version. @rbeuthin can you see the value of the app-type blueprints yet?

### CODE REVIEW

**Review by alexbunardzic — CHANGES_REQUESTED** [review]
Willy, brilliant article that really nails it! Your writing style is exemplary. Many compliments on the structure, the content, the flow -- a truly enjoyable read :)

Minor nitpicks: in the opening sentence you wrote "an continuous" -- I think it should be "a continuous". (there was another minor syntax glitch that I found while reading but now I cannot see it; if I find it later on I'll ping you). Other than this, everything else is perfect.

A suggestion: you made a very strong point for the self-serve model. I think self-serve is the real clincher here. Is there a way to potentiate it even more? I believe we need to really drill it down so that everyone understands that sky is the limit and you are absolutely free to craft your precious snowflakes till the cows come home, but all those snowflakes will undergo careful scrutiny before they get approved (eventually).

As a side note, I'd suggest you start seriously thinking about preparing a training course for us: "How to write effective, elegant technical articles". We could all benefit from your vast expertise in this area.

**Review by erwsch1 — DISMISSED** [review]

**Comment by wpschaub** [comment]
@said-akram-wcbbc as discussed it is important to get your thoughts added to the post, in terms of:

- Why do you believe in the blueprints?
- Why are you not, like other engineers, pushing back on our plan for consistent pipeline blueprints?
- Why will you, as engineer, not loose ability to influence and change the blueprints?
- What are you planning next :)

**Comment by wpschaub** [comment]
@erwsch1 @solicitfeedback @said-akram-wcbbc latest updates from Said look great. Please (re-)review and approve, so that we can proceed with the series, with only two parts to go q;-)

**Comment by wpschaub** [comment]
@erwsch1 @solicitfeedback @said-akram-wcbbc latest updates from Said look great. Please (re-)review and approve, so that we can

**Review by wsbctechnicalblog — CHANGES_REQUESTED** [review]
For consistency, I recommend modifying lines:

1. Submit a **Pull-Request** with your **starter** template to our CeS Templates repo. .
1. Submit a **Pull-Request** with your **app-type** template to our CeS AppTemplates repo. 

To:

1. Submit a **Pull Request** with your **starter** template to our CeS Templates repo.
1. Submit a **Pull Request** with your **app-type** template to our CeS AppTemplates repo.

**Comment by wpschaub** [comment]
@wsbctechnicalblog once we have thumbs up from @said-akram-wcbbc and @erwsch1, you can click the launch button.

**Review by wsbctechnicalblog — CHANGES_REQUESTED** [review]
I recommend for consistency to remove dashes from Pull-Request

**Review by said-akram-wcbbc — DISMISSED** [review]

**Review by solicitfeedback — APPROVED** [review]

**Review by wsbctechnicalblog — APPROVED** [review]

**Review by said-akram-wcbbc — APPROVED** [review]

**Review by erwsch1 — APPROVED** [review]

**Comment by wpschaub** [comment]
@alexbunardzic @wsbctechnicalblog looks like we have approval to pull the trigger! We just need you to confirm that all changes requested by @alexbunardzic are done.

**Review by erwsch1 — APPROVED** [review]

**Pull request merged**
